const STORAGE_KEY='magnat-flower-html-v1';
// Вставьте значения из Supabase: Project Settings → API.
const SUPABASE_URL='https://fjiuqgkwaaqkauyjbdkd.supabase.co';
const SUPABASE_ANON_KEY='sb_publishable_sQwt6XiafcbTcbmpocLM_Q_YdvKNK8y';
const AUTH_REDIRECT_URL='https://rafwonko-stack.github.io/Magnat-Flower/';
const CLOUD_READY=/^https:\/\/[^/]+\.supabase\.co$/.test(SUPABASE_URL)&&!SUPABASE_ANON_KEY.startsWith('PASTE_');
const SESSION_KEY='magnat-flower-supabase-session';
const productCategories=['Цветы','Зелень','Упаковка','Аксессуары','Мишки'];
const baseExpenseCategories=['Зарплата','Мусор','Электроэнергия','Аренда','Налог','Wi-Fi','Услуги','Доставка','Коммунальные услуги','Другое'];
const kindLabels={sale:'Продажа',receipt:'Поступление',writeoff:'Списание',refund:'Возврат',cancel:'Отмена',expense:'Расход',inventory:'Инвентаризация','edit-product':'Изменение товара','edit-recipe':'Изменение букета'};
const $=selector=>document.querySelector(selector);
const esc=value=>String(value??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const cents=value=>Math.round(Number(value||0)*100);
const money=value=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:2}).format((value||0)/100)+' сом';
const dateText=value=>new Date(value).toLocaleString('ru-RU',{timeZone:'Asia/Bishkek'});
const dayKey=value=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bishkek',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(value));
const today=()=>dayKey(Date.now());
const label=p=>p.name+(p.sizeCm?` · ${p.sizeCm} см`:'');
const emptyState=()=>({products:[],recipes:[],counterparties:[],documents:[],expenseCategories:[...baseExpenseCategories]});
function load(key=STORAGE_KEY){try{const data=JSON.parse(localStorage.getItem(key));return data&&Array.isArray(data.products)?{...emptyState(),...data}:emptyState()}catch{return emptyState()}}
let state=load(),activeTab='stock',session=null,cloudRevision=0,cloudDirty=false,cloudSaving=false,authMode='login';
const cacheKey=()=>session?.user?.id?`${STORAGE_KEY}:${session.user.id}`:STORAGE_KEY;
function save(message='Сохранено. Данные магазина обновлены.'){localStorage.setItem(cacheKey(),JSON.stringify(state));render();notice(message);queueCloudSave()}
function notice(message,error=false){$('#notice').innerHTML=`<div class="${error?'alert':'notice'}"><span>${esc(message)}</span><button data-dismiss>×</button></div>`;setTimeout(()=>{if($('#notice').textContent.includes(message))$('#notice').innerHTML=''},4500)}
function product(id){return state.products.find(item=>item.id===id)}
function recipe(id){return state.recipes.find(item=>item.id===id)}
function counterparty(id){return state.counterparties.find(item=>item.id===id)}
function recipePrice(item){return item.price+item.decorationFee}
function totals(docs=state.documents){return docs.reduce((sum,d)=>{for(const key of ['revenue','cost','loss','expenses','purchases','decoration'])sum[key]+=d[key]||0;if(d.kind==='sale')sum.sales++;if(d.kind==='receipt')sum.receipts++;if(d.kind==='writeoff')sum.writeoffs++;return sum},{revenue:0,cost:0,loss:0,expenses:0,purchases:0,decoration:0,sales:0,receipts:0,writeoffs:0})}
function addDocument(data){state.documents.unshift({id:uid(),created:Date.now(),summary:'',amount:0,note:'',counterpartyName:null,reversedBy:null,reverseOf:null,revenue:0,cost:0,loss:0,expenses:0,purchases:0,decoration:0,...data})}

function render(){
  const all=totals(),stock=state.products.reduce((sum,p)=>sum+p.stock,0),value=state.products.reduce((sum,p)=>sum+p.stock*p.cost,0),low=state.products.filter(p=>p.stock<=p.minimum).length;
  $('#stats').innerHTML=`<article><span>Товары на складе</span><strong>${stock}<small> шт.</small></strong><p>${state.products.length} товаров и вариантов</p></article><article><span>Стоимость остатков</span><strong>${money(value)}</strong><p>По средней себестоимости</p></article><article><span>Выручка за всё время</span><strong>${money(all.revenue)}</strong><p>${all.sales} продаж</p></article><article class="attention"><span>Требуют пополнения</span><strong>${low}<small> позиций</small></strong><p>На уровне минимального остатка</p></article>`;
  document.querySelectorAll('[data-tab]').forEach(button=>button.classList.toggle('active',button.dataset.tab===activeTab));
  ({stock:renderStock,recipes:renderRecipes,counterparties:renderCounterparties,expenses:renderExpenses,history:renderHistory,reports:renderReports}[activeTab]||renderStock)();
}
function renderStock(){
  const rows=state.products.map(p=>{const expense=(p.purchasePrice||p.cost)*p.stock,profit=(p.price-(p.purchasePrice||p.cost))*p.stock;return `<tr><td class="item-name" data-label="Товар">${esc(label(p))}</td><td data-label="Категория">${esc(p.category)}</td><td data-label="Остаток"><div class="inline-value"><input data-inline-product="${p.id}" data-field="stock" type="number" min="0" step="1" value="${p.stock}" aria-label="Остаток ${esc(label(p))}"><span>шт.</span></div></td><td data-label="Закупочная цена"><div class="inline-value"><input data-inline-product="${p.id}" data-field="purchasePrice" type="number" min="0" step="0.01" value="${(p.purchasePrice||0)/100}" aria-label="Закупочная цена ${esc(label(p))}"><span>сом</span></div></td><td data-label="Цена продажи"><div class="inline-value"><input data-inline-product="${p.id}" data-field="price" type="number" min="0.01" step="0.01" value="${(p.price||0)/100}" aria-label="Цена продажи ${esc(label(p))}"><span>сом</span></div></td><td data-label="Расход на остаток"><strong>${money(expense)}</strong></td><td data-label="Прибыль с остатка"><strong class="${profit<0?'negative':'positive'}">${money(profit)}</strong></td><td data-label="Состояние"><span class="badge ${p.stock<=p.minimum?'warn':''}">${p.stock===0?'Нет в наличии':p.stock<=p.minimum?'Пополнить':'В наличии'}</span></td><td data-label="Действие"><button data-edit-product="${p.id}">Карточка</button></td></tr>`}).join('');
  $('#content').innerHTML=`<section class="panel"><div class="panel-head"><div><h2>Товары и остатки</h2><p>Цифры можно менять прямо в строке. Расход и прибыль рассчитаны для текущего остатка.</p></div><div class="actions"><button data-action="inventory">Инвентаризация</button><button data-action="receipt">↓ Поступление</button><button data-action="writeoff">Списание</button><button class="primary" data-action="product">＋ Товар</button></div></div>${rows?`<div class="table-wrap"><table class="responsive-table stock-table"><thead><tr><th>Наименование / размер</th><th>Категория</th><th>Остаток</th><th>Закупочная цена</th><th>Цена продажи</th><th>Расход на остаток</th><th>Прибыль с остатка</th><th>Состояние</th><th></th></tr></thead><tbody>${rows}</tbody></table></div>`:`<div class="empty"><h3>Добавьте первый товар</h3><p>Укажите цены, затем оформите поступление на склад.</p><button data-action="product">Добавить товар</button></div>`}</section>`;
}
function renderRecipes(){
 const cards=state.recipes.map(r=>{const composition=r.parts.map(part=>`${esc(label(product(part.productId)||{name:'Удалённый товар'}))} × ${part.quantity}`).join(', ');const cost=r.parts.reduce((s,part)=>s+(product(part.productId)?.cost||product(part.productId)?.purchasePrice||0)*part.quantity,0),sale=recipePrice(r),profit=sale-cost;return `<article class="recipe"><h3>✿ ${esc(r.name)}</h3><p>${composition}</p><div class="recipe-row"><span>Букет</span><b>${money(r.price)}</b></div><div class="recipe-row"><span>Оформление</span><b>${money(r.decorationFee)}</b></div><div class="recipe-row recipe-total"><span>Цена продажи</span><b>${money(sale)}</b></div><div class="recipe-row recipe-expense"><span>Расходы</span><b>− ${money(cost)}</b></div><div class="recipe-row recipe-profit"><span>Прибыль</span><b>${money(profit)}</b></div><button data-edit-recipe="${r.id}">Изменить</button></article>`}).join('');
 $('#content').innerHTML=`<section class="panel"><div class="panel-head"><div><h2>Букеты</h2><p>Состав, себестоимость и оформление</p></div><button class="primary" data-action="recipe">＋ Создать букет</button></div>${cards?`<div class="recipe-grid">${cards}</div>`:`<div class="empty"><h3>Соберите первый букет</h3><p>Сначала добавьте товары, затем выберите состав и оформление.</p><button data-action="recipe" ${state.products.length?'':'disabled'}>Создать букет</button></div>`}</section>`;
}
function renderCounterparties(){
 const rows=state.counterparties.map(c=>`<tr><td data-label="Тип"><span class="badge">${c.type==='customer'?'Клиент':'Поставщик'}</span></td><td class="item-name" data-label="Название">${esc(c.name)}</td><td data-label="Телефон">${esc(c.phone||'—')}</td><td data-label="Комментарий">${esc(c.note||'—')}</td><td data-label="Действие"><button class="danger" data-delete-counterparty="${c.id}">Удалить</button></td></tr>`).join('');
 $('#content').innerHTML=`<section class="panel"><div class="panel-head"><div><h2>Клиенты и поставщики</h2><p>Контакты для продаж и поступлений</p></div></div><div class="counterparty-layout"><form class="side-form" id="counterparty-form"><h3>Новый контрагент</h3><label>Тип<select name="type"><option value="customer">Клиент</option><option value="supplier">Поставщик</option></select></label><label>Название или имя<input name="name" required maxlength="100"></label><label>Телефон<input name="phone" type="tel" maxlength="30" placeholder="+996 555 123 456"></label><label>Комментарий<textarea name="note" maxlength="300" rows="3"></textarea></label><button class="primary">Добавить</button></form><div class="table-wrap">${rows?`<table class="responsive-table"><thead><tr><th>Тип</th><th>Название</th><th>Телефон</th><th>Комментарий</th><th></th></tr></thead><tbody>${rows}</tbody></table>`:`<div class="empty"><h3>Справочник пуст</h3><p>Добавьте первого клиента или поставщика.</p></div>`}</div></div></section>`;
}
function renderExpenses(){
 const expenses=state.documents.filter(d=>d.kind==='expense'&&!d.reversedBy).slice(0,50),sum=expenses.reduce((s,d)=>s+d.expenses,0),rows=expenses.map(d=>`<tr><td data-label="Дата">${dateText(d.created)}</td><td data-label="Категория"><span class="badge">${esc(d.expenseCategory)}</span></td><td data-label="Сумма">${money(d.expenses)}</td><td data-label="Комментарий">${esc(d.note)}</td><td data-label="Действие"><button data-reverse="${d.id}">Отменить</button></td></tr>`).join('');
 $('#content').innerHTML=`<section class="panel"><div class="panel-head"><div><h2>Расходы магазина</h2><p>Всего активных расходов: ${money(sum)}</p></div><button class="primary" data-action="expense">＋ Новый расход</button></div>${rows?`<div class="table-wrap"><table class="responsive-table"><thead><tr><th>Дата</th><th>Категория</th><th>Сумма</th><th>Комментарий</th><th></th></tr></thead><tbody>${rows}</tbody></table></div>`:`<div class="empty"><h3>Расходов пока нет</h3><p>Добавьте аренду, зарплату, налог или другой расход.</p></div>`}</section>`;
}
function renderHistory(){
 const rows=state.documents.slice(0,100).map(d=>`<tr><td data-label="Дата">${dateText(d.created)}</td><td data-label="Операция"><span class="badge ${d.kind==='writeoff'?'warn':''}">${kindLabels[d.kind]||esc(d.kind)}</span></td><td data-label="Контрагент">${esc(d.counterpartyName||'—')}</td><td data-label="Состав">${esc(d.summary)}</td><td data-label="Сумма">${money(d.amount)}</td><td data-label="Комментарий">${esc(d.note||'—')}</td><td data-label="Действие">${d.reversedBy?'<span class="badge gray">Отменено / возвращено</span>':['sale','receipt','writeoff','inventory','expense'].includes(d.kind)?`<button data-reverse="${d.id}">${d.kind==='sale'?'Возврат':'Отменить'}</button>`:'—'}</td></tr>`).join('');
 $('#content').innerHTML=`<section class="panel"><div class="panel-head"><div><h2>Журнал операций</h2><p>Последние 100 документов · отмены и возвраты сохраняются отдельно</p></div></div>${rows?`<div class="table-wrap"><table class="responsive-table"><thead><tr><th>Дата</th><th>Операция</th><th>Контрагент</th><th>Состав</th><th>Сумма</th><th>Комментарий</th><th>Действия</th></tr></thead><tbody>${rows}</tbody></table></div>`:`<div class="empty"><h3>Операций пока нет</h3><p>Поступления, продажи и списания появятся здесь.</p></div>`}</section>`;
}
function renderReports(){
 const now=today(),month=now.slice(0,7)+'-01';
 $('#content').innerHTML=`<section class="panel"><div class="panel-head"><div><h2>Отчёт магазина</h2><p>Единый период для продаж, списаний и расходов · Бишкек</p></div><div class="report-controls"><label>С<input id="report-from" type="date" value="${month}"></label><label>По<input id="report-to" type="date" value="${now}"></label><button data-period="today">Сегодня</button><button data-period="month">Месяц</button><button data-period="all">За всё время</button></div></div><div id="report-result"></div></section>`;updateReport(month,now);
}
function updateReport(from,to){
 const docs=state.documents.filter(d=>(!from||dayKey(d.created)>=from)&&(!to||dayKey(d.created)<=to));const r=totals(docs),breakdown={};docs.forEach(d=>{if(d.expenses)breakdown[d.expenseCategory||'Другое']=(breakdown[d.expenseCategory||'Другое']||0)+d.expenses});
 const pairs=[['Количество продаж',r.sales,true],['Выручка',r.revenue],['В том числе оформление',r.decoration],['Себестоимость проданного',r.cost],['Валовая прибыль',r.revenue-r.cost],['Стоимость списаний и расхождений',r.loss],['Расходы магазина',r.expenses],['Прибыль после расходов',r.revenue-r.cost-r.loss-r.expenses],['Закупки за период',r.purchases]];
 $('#report-result').innerHTML=`<div class="report-columns"><div class="report-list">${pairs.map(([name,value,count])=>`<div class="${name==='Прибыль после расходов'?'report-profit':''}"><span>${name}</span><strong>${count?value:money(value)}</strong></div>`).join('')}<p>Обе даты включены. Закупки показаны отдельно и повторно не вычитаются из прибыли.</p></div><div class="expense-breakdown"><h3>Расходы по категориям</h3>${Object.entries(breakdown).filter(([,v])=>v).sort((a,b)=>b[1]-a[1]).map(([name,value])=>`<div class="expense-row"><span>${esc(name)}</span><strong>${money(value)}</strong></div>`).join('')||'<p>В выбранном периоде расходов нет.</p>'}</div></div>`;
}

function showModal(title,description,body){$('#modal-content').innerHTML=`<div class="modal-head"><div><h2>${title}</h2><p>${description}</p></div><button class="close" data-close aria-label="Закрыть">×</button></div>${body}`;$('#modal').showModal()}
function closeModal(){$('#modal').close()}
const options=(items,selected='')=>items.map(item=>`<option value="${item.value}" ${item.value===selected?'selected':''}>${esc(item.label)}</option>`).join('');
const productOptions=()=>options(state.products.map(p=>({value:p.id,label:`${label(p)} · ${p.stock} шт.`})));
function lineHtml(kind,index=0,line={id:'',quantity:1,cost:''}){const recipeOpts=kind==='sale'?state.recipes.map(r=>({value:r.id,label:`Букет · ${r.name}`})):[];const list=[...state.products.map(p=>({value:p.id,label:`${label(p)} · ${p.stock} шт.`})),...recipeOpts];return `<div class="form-line ${kind==='receipt'?'receipt':''}" data-line><select name="item" required><option value="">Выберите товар</option>${options(list,line.id)}</select><input name="quantity" aria-label="Количество" type="number" min="1" step="1" value="${line.quantity}" required>${kind==='receipt'?`<input name="cost" aria-label="Цена закупки" type="number" min="0.01" step="0.01" value="${line.cost}" placeholder="сом за шт." required>`:''}<button type="button" data-remove-line>×</button></div>`}
function openProduct(id){const p=id?product(id):null;showModal(p?'Изменить товар':'Новый товар','Каждый размер — отдельный товар со своими ценами и остатком.',`<form id="product-form" data-id="${p?.id||''}"><label>Название<input name="name" required maxlength="100" value="${esc(p?.name||'')}" placeholder="Например, Мишка плюшевый"></label><label>Категория<select name="category">${options(productCategories.map(x=>({value:x,label:x})),p?.category||'Цветы')}</select></label><div id="size-field" ${p?.category==='Мишки'?'':'hidden'}><label>Размер мишки, см<input name="size" type="number" min="1" max="300" value="${p?.sizeCm||''}"></label></div><div class="form-grid"><label>Закупочная цена, сом<input name="purchase" type="number" min="0" step="0.01" required value="${(p?.purchasePrice||0)/100}"></label><label>Цена продажи, сом<input name="price" type="number" min="0.01" step="0.01" required value="${p?p.price/100:''}" placeholder="По сколько будете продавать"></label></div><label>Минимальный остаток<input name="minimum" type="number" min="0" step="1" required value="${p?.minimum??5}"></label><p class="form-hint">Остаток можно изменить в таблице склада или через «Поступление».</p><div class="modal-actions"><button type="button" data-close>Отмена</button><button class="primary">Сохранить</button></div></form>`)}
function openRecipe(id){const r=id?recipe(id):null;if(!state.products.length)return notice('Сначала добавьте хотя бы один товар.',true);const lines=r?.parts||[{id:'',quantity:1}];showModal(r?'Изменить букет':'Новый букет','Цена букета и оформление суммируются. Состав списывается при продаже.',`<form id="recipe-form" data-id="${r?.id||''}"><label>Название<input name="name" required maxlength="100" value="${esc(r?.name||'')}" placeholder="Например, 15 красных роз"></label><div class="form-grid"><label>Цена букета без оформления, сом<input name="price" type="number" min="0.01" step="0.01" required value="${r?r.price/100:''}"></label><label>Оформление, сом<input name="decoration" type="number" min="0" step="0.01" required value="${(r?.decorationFee||0)/100}"></label></div><div class="line-head"><span>Состав букета</span><span>Количество</span></div><div id="lines">${lines.map((l,i)=>lineHtml('recipe',i,{id:l.productId,quantity:l.quantity})).join('')}</div><button type="button" data-add-line="recipe">＋ Добавить позицию</button><div class="modal-actions"><button type="button" data-close>Отмена</button><button class="primary">Сохранить</button></div></form>`)}
function openTransaction(kind){if(!state.products.length)return notice('Сначала добавьте товар.',true);const cpType=kind==='sale'?'customer':'supplier',cp=state.counterparties.filter(c=>c.type===cpType);showModal(kindLabels[kind],'Операция сохранится в журнале и обновит остатки.',`<form id="transaction-form" data-kind="${kind}">${['sale','receipt'].includes(kind)?`<label>${kind==='sale'?'Клиент':'Поставщик'}<select name="counterparty"><option value="">Не выбран</option>${options(cp.map(c=>({value:c.id,label:c.name})))}</select></label>`:''}<div class="line-head"><span>Товары</span><span>Количество${kind==='receipt'?' / закупка':''}</span></div><div id="lines">${lineHtml(kind)}</div><button type="button" data-add-line="${kind}">＋ Добавить позицию</button><label>${kind==='writeoff'?'Причина списания':'Комментарий'}<input name="note" maxlength="300" ${kind==='writeoff'?'required':''}></label><div id="transaction-total"></div><div class="modal-actions"><button type="button" data-close>Отмена</button><button class="primary">Сохранить</button></div></form>`);updateTransactionTotal()}
function openExpense(){showModal('Новый расход','Расход попадёт в отчёт за выбранную дату.',`<form id="expense-form"><label>Дата расхода<input name="date" type="date" value="${today()}" required></label><label>Категория<select name="category">${options(state.expenseCategories.map(x=>({value:x,label:x})))}</select></label><label>Новая категория (необязательно)<input name="newCategory" maxlength="60" placeholder="Например, Реклама"></label><label>Сумма, сом<input name="amount" type="number" min="0.01" step="0.01" required></label><label>Причина / комментарий<input name="note" maxlength="300" required></label><div class="modal-actions"><button type="button" data-close>Отмена</button><button class="primary">Сохранить</button></div></form>`)}
function openInventory(){if(!state.products.length)return notice('Склад пока пуст.',true);showModal('Инвентаризация','Введите фактически пересчитанное количество.',`<form id="inventory-form"><div class="inventory-list">${state.products.map(p=>`<div class="inventory-row"><span>${esc(label(p))}<small>По системе: ${p.stock} шт.</small></span><input name="${p.id}" type="number" min="0" step="1" value="${p.stock}" required></div>`).join('')}</div><label>Комментарий<input name="note" maxlength="300" required value="Сверка склада"></label><div class="modal-actions"><button type="button" data-close>Отмена</button><button class="primary">Сохранить</button></div></form>`)}
function updateTransactionTotal(){const form=$('#transaction-form');if(!form||form.dataset.kind!=='sale')return;let sum=0;form.querySelectorAll('[data-line]').forEach(line=>{const id=line.querySelector('[name=item]').value,q=Number(line.querySelector('[name=quantity]').value)||0;sum+=(product(id)?.price??(recipe(id)?recipePrice(recipe(id)):0))*q});$('#transaction-total').innerHTML=`<div class="total"><span>К оплате</span><strong>${money(sum)}</strong></div>`}
function uniqueLines(form){const lines=[...form.querySelectorAll('[data-line]')].map(row=>({id:row.querySelector('[name=item]').value,quantity:Number(row.querySelector('[name=quantity]').value),cost:cents(row.querySelector('[name=cost]')?.value)}));if(lines.some(x=>!x.id||!Number.isInteger(x.quantity)||x.quantity<1))throw Error('Выберите товары и укажите количество.');if(new Set(lines.map(x=>x.id)).size!==lines.length)throw Error('Один товар нельзя указывать дважды.');return lines}

function updateProductNumber(input){
 const p=product(input.dataset.inlineProduct),field=input.dataset.field,value=Number(input.value);if(!p)return;
 if(!Number.isFinite(value)||value<0||(field==='stock'&&!Number.isInteger(value))){notice('Введите корректное неотрицательное число.',true);render();return}
 if(field==='price'&&value<=0){notice('Цена продажи должна быть больше нуля.',true);render();return}
 const previous={stock:p.stock,purchasePrice:p.purchasePrice,price:p.price,cost:p.cost};
 if(field==='stock')p.stock=value;
 if(field==='purchasePrice'){p.purchasePrice=cents(value);p.cost=p.purchasePrice}
 if(field==='price')p.price=cents(value);
 if(previous.stock===p.stock&&previous.purchasePrice===p.purchasePrice&&previous.price===p.price)return;
 const names={stock:'остаток',purchasePrice:'закупочная цена',price:'цена продажи'};
 addDocument({kind:field==='stock'?'inventory':'edit-product',summary:`${label(p)}: изменён ${names[field]}`,note:'Изменено прямо в строке склада',stockBefore:field==='stock'?[{id:p.id,...previous}]:undefined});
 save(`${label(p)}: данные обновлены.`);
}

document.addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;if(b.dataset.dismiss!==undefined)$('#notice').innerHTML='';if(b.dataset.close!==undefined)closeModal();if(b.dataset.tab){activeTab=b.dataset.tab;render()}if(b.dataset.action){({product:()=>openProduct(),recipe:()=>openRecipe(),sale:()=>openTransaction('sale'),receipt:()=>openTransaction('receipt'),writeoff:()=>openTransaction('writeoff'),expense:openExpense,inventory:openInventory}[b.dataset.action]||(()=>{}))()}if(b.dataset.editProduct)openProduct(b.dataset.editProduct);if(b.dataset.editRecipe)openRecipe(b.dataset.editRecipe);if(b.dataset.addLine){$('#lines').insertAdjacentHTML('beforeend',lineHtml(b.dataset.addLine,$$('#lines [data-line]')?.length||0));updateTransactionTotal()}if(b.dataset.removeLine){const lines=b.closest('#lines');if(lines.children.length>1)b.closest('[data-line]').remove();updateTransactionTotal()}if(b.dataset.reverse)reverseDocument(b.dataset.reverse);if(b.dataset.deleteCounterparty){if(confirm('Удалить контрагента из справочника? История операций сохранится.')){state.counterparties=state.counterparties.filter(c=>c.id!==b.dataset.deleteCounterparty);save('Контрагент удалён.')}}if(b.dataset.period){const from=$('#report-from'),to=$('#report-to'),now=today();if(b.dataset.period==='today')from.value=to.value=now;if(b.dataset.period==='month'){from.value=now.slice(0,7)+'-01';to.value=now}if(b.dataset.period==='all'){from.value='';to.value=''}updateReport(from.value,to.value)}});
document.addEventListener('input',event=>{if(event.target.closest('#transaction-form'))updateTransactionTotal();if(event.target.id==='report-from'||event.target.id==='report-to')updateReport($('#report-from').value,$('#report-to').value)});
document.addEventListener('change',event=>{if(event.target.matches('[data-inline-product]'))updateProductNumber(event.target);if(event.target.matches('#product-form [name=category]'))$('#size-field').hidden=event.target.value!=='Мишки';if(event.target.matches('#transaction-form[data-kind=receipt] [name=item]')){const row=event.target.closest('[data-line]'),p=product(event.target.value);row.querySelector('[name=cost]').value=p?p.purchasePrice/100:''}});
document.addEventListener('submit',event=>{event.preventDefault();try{if(event.target.id==='auth-form'){void submitAuth(event.target);return}if(event.target.id==='product-form')submitProduct(event.target);if(event.target.id==='recipe-form')submitRecipe(event.target);if(event.target.id==='transaction-form')submitTransaction(event.target);if(event.target.id==='expense-form')submitExpense(event.target);if(event.target.id==='inventory-form')submitInventory(event.target);if(event.target.id==='counterparty-form')submitCounterparty(event.target)}catch(error){notice(error.message||'Проверьте введённые данные.',true)}});
function $$(selector){return document.querySelectorAll(selector)}
function submitProduct(form){const data=new FormData(form),category=data.get('category'),size=category==='Мишки'?Number(data.get('size')):null;if(category==='Мишки'&&(!Number.isInteger(size)||size<1))throw Error('Укажите размер мишки.');const current=product(form.dataset.id),item={id:current?.id||uid(),name:String(data.get('name')).trim(),category,sizeCm:size,stock:current?.stock||0,cost:current?.cost||0,purchasePrice:cents(data.get('purchase')),price:cents(data.get('price')),minimum:Number(data.get('minimum'))};if(!item.name||item.price<=0)throw Error('Укажите название и розничную цену.');if(current){Object.assign(current,item);addDocument({kind:'edit-product',summary:`Товар изменён: ${label(item)}`,note:'Карточка товара обновлена'})}else state.products.push(item);closeModal();save(current?'Карточка товара изменена.':'Товар добавлен.')}
function submitRecipe(form){const data=new FormData(form),lines=uniqueLines(form),current=recipe(form.dataset.id),item={id:current?.id||uid(),name:String(data.get('name')).trim(),price:cents(data.get('price')),decorationFee:cents(data.get('decoration')),parts:lines.map(x=>({productId:x.id,quantity:x.quantity}))};if(!item.name||item.price<=0)throw Error('Укажите название и цену букета.');if(current){Object.assign(current,item);addDocument({kind:'edit-recipe',summary:`Букет изменён: ${item.name}`,note:'Карточка букета обновлена'})}else state.recipes.push(item);closeModal();save(current?'Букет изменён.':'Букет создан.')}
function expandLines(kind,lines){const quantities=new Map(),summary=[],saleItems=[];let revenue=0,decoration=0;const add=(id,q)=>quantities.set(id,(quantities.get(id)||0)+q);for(const line of lines){const p=product(line.id);if(p){add(p.id,line.quantity);summary.push(`${label(p)} × ${line.quantity}`);if(kind==='sale'){revenue+=p.price*line.quantity;saleItems.push({name:label(p),quantity:line.quantity})}}else if(kind==='sale'){const r=recipe(line.id);if(!r)throw Error('Букет не найден.');r.parts.forEach(part=>add(part.productId,part.quantity*line.quantity));summary.push(`${r.name} × ${line.quantity}`);revenue+=recipePrice(r)*line.quantity;decoration+=r.decorationFee*line.quantity;saleItems.push({name:r.name,quantity:line.quantity})}else throw Error('Товар не найден.')}return{quantities,summary:summary.join(', '),revenue,decoration,saleItems}}
function submitTransaction(form){const kind=form.dataset.kind,data=new FormData(form),lines=uniqueLines(form),expanded=expandLines(kind,lines),stockBefore=[...expanded.quantities.keys()].map(id=>{const p=product(id);return{id,stock:p.stock,cost:p.cost,purchasePrice:p.purchasePrice}});let cost=0,loss=0,purchases=0;for(const [id,qty] of expanded.quantities){const p=product(id);if(kind==='receipt'){const source=lines.find(l=>l.id===id),unit=source.cost;if(unit<=0)throw Error('Укажите цену закупки.');const total=p.stock*p.cost+qty*unit;p.cost=Math.round(total/(p.stock+qty));p.stock+=qty;p.purchasePrice=unit;purchases+=qty*unit}else{if(p.stock<qty)throw Error(`Недостаточно товара «${label(p)}». На складе: ${p.stock}.`);p.stock-=qty;if(kind==='sale')cost+=p.cost*qty;else loss+=p.cost*qty}}
 const cp=counterparty(data.get('counterparty'));addDocument({kind,summary:expanded.summary,amount:kind==='sale'?expanded.revenue:kind==='receipt'?purchases:loss,note:String(data.get('note')||''),counterpartyName:cp?.name||null,revenue:kind==='sale'?expanded.revenue:0,cost,loss,purchases,decoration:expanded.decoration,stockBefore});closeModal();save(`${kindLabels[kind]}: операция сохранена.`)}
function submitExpense(form){const data=new FormData(form),custom=String(data.get('newCategory')||'').trim(),category=custom||data.get('category'),amount=cents(data.get('amount'));if(amount<=0)throw Error('Укажите сумму расхода.');if(custom&&!state.expenseCategories.includes(custom))state.expenseCategories.push(custom);const created=new Date(`${data.get('date')}T06:00:00Z`).getTime();addDocument({kind:'expense',created,summary:String(category),amount,expenses:amount,expenseCategory:String(category),note:String(data.get('note')).trim()});closeModal();save('Расход сохранён.')}
function submitInventory(form){const data=new FormData(form),changes=[],stockBefore=[];let loss=0;for(const p of state.products){const actual=Number(data.get(p.id));if(!Number.isInteger(actual)||actual<0)throw Error('Фактический остаток должен быть целым числом.');if(actual!==p.stock){stockBefore.push({id:p.id,stock:p.stock,cost:p.cost,purchasePrice:p.purchasePrice});loss+=(p.stock-actual)*p.cost;changes.push(`${label(p)}: ${p.stock} → ${actual}`);p.stock=actual}}if(!changes.length)throw Error('Расхождений нет. Остатки совпадают.');addDocument({kind:'inventory',summary:changes.join(', '),amount:loss,loss,note:String(data.get('note')).trim(),stockBefore});closeModal();save('Инвентаризация сохранена.')}
function submitCounterparty(form){const data=new FormData(form),name=String(data.get('name')).trim();if(!name)throw Error('Укажите имя или название.');state.counterparties.push({id:uid(),type:data.get('type'),name,phone:String(data.get('phone')).trim(),note:String(data.get('note')).trim()});form.reset();save('Контрагент добавлен.')}
function reverseDocument(id){const original=state.documents.find(d=>d.id===id);if(!original||original.reversedBy)return;if(!confirm(original.kind==='sale'?'Оформить полный возврат продажи?':'Отменить эту операцию?'))return;if(original.stockBefore){for(const snap of original.stockBefore){const p=product(snap.id);if(p){p.stock=snap.stock;p.cost=snap.cost;p.purchasePrice=snap.purchasePrice}}}const reverseId=uid();original.reversedBy=reverseId;state.documents.unshift({id:reverseId,created:Date.now(),kind:original.kind==='sale'?'refund':'cancel',summary:`${original.kind==='sale'?'Полный возврат':'Отмена'}: ${original.summary}`,amount:-original.amount,note:'Обратная операция',counterpartyName:original.counterpartyName,reversedBy:null,reverseOf:original.id,revenue:-(original.revenue||0),cost:-(original.cost||0),loss:-(original.loss||0),expenses:-(original.expenses||0),purchases:-(original.purchases||0),decoration:-(original.decoration||0)});save(original.kind==='sale'?'Возврат оформлен.':'Операция отменена.')}

$('#modal').addEventListener('click',event=>{if(event.target===$('#modal'))closeModal()});

function setSyncStatus(status,title){const dot=$('#sync-dot');if(!dot)return;dot.className=`sync-dot ${status}`;dot.title=title||''}
function authHeaders(token=session?.access_token){return{'apikey':SUPABASE_ANON_KEY,...(token?{'Authorization':`Bearer ${token}`}:{ }),'Content-Type':'application/json'}}
async function cloudFetch(path,options={},useSession=true){
  const response=await fetch(`${SUPABASE_URL}${path}`,{...options,headers:{...authHeaders(useSession?session?.access_token:null),...(options.headers||{})}});
  if(response.status===401&&useSession&&session?.refresh_token){await refreshSession();return cloudFetch(path,options,true)}
  const text=await response.text();let data=null;try{data=text?JSON.parse(text):null}catch{data=text}
  if(!response.ok){const error=new Error(data?.message||data?.error_description||data?.hint||data?.details||data?.error||`Ошибка сервера: ${response.status}`);error.code=data?.code;throw error}
  return data;
}
function storeSession(value){session=value;value?localStorage.setItem(SESSION_KEY,JSON.stringify(value)):localStorage.removeItem(SESSION_KEY)}
async function refreshSession(){
  const current=session;if(!current?.refresh_token)throw Error('Сеанс завершён. Войдите снова.');
  const next=await cloudFetch('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:JSON.stringify({refresh_token:current.refresh_token})},false);storeSession(next);return next;
}
async function submitAuth(form){
  const button=$('#auth-submit'),error=$('#auth-error'),data=new FormData(form);button.disabled=true;error.textContent='';
  try{
    const endpoint=authMode==='signup'?`/auth/v1/signup?redirect_to=${encodeURIComponent(AUTH_REDIRECT_URL)}`:'/auth/v1/token?grant_type=password';
    const result=await cloudFetch(endpoint,{method:'POST',body:JSON.stringify({email:String(data.get('email')).trim(),password:String(data.get('password'))})},false);
    if(!result.access_token){error.textContent='Аккаунт создан. Подтвердите email по ссылке из письма, затем войдите.';authMode='login';updateAuthMode();return}
    storeSession(result);await enterApp();
  }catch(e){error.textContent=e.message||'Не удалось выполнить вход.'}finally{button.disabled=false}
}
async function restoreSessionFromRedirect(){
  const params=new URLSearchParams(location.hash.replace(/^#/,'')),accessToken=params.get('access_token'),refreshToken=params.get('refresh_token');
  if(!accessToken||!refreshToken)return false;
  try{
    const response=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:authHeaders(accessToken)});
    const user=await response.json();
    if(!response.ok)throw Error(user?.message||'Не удалось подтвердить email.');
    const expiresIn=Number(params.get('expires_in'))||3600;
    storeSession({access_token:accessToken,refresh_token:refreshToken,token_type:params.get('token_type')||'bearer',expires_in:expiresIn,expires_at:Math.floor(Date.now()/1000)+expiresIn,user});
    history.replaceState(null,'',location.pathname+location.search);
    return true;
  }catch(error){
    history.replaceState(null,'',location.pathname+location.search);
    $('#auth-page').hidden=false;$('#auth-error').textContent=error.message||'Не удалось подтвердить email.';
    return false;
  }
}
function updateAuthMode(){const signup=authMode==='signup';$('#auth-title').textContent=signup?'Создание аккаунта':'Вход в систему';$('#auth-description').textContent=signup?'Создайте защищённую облачную базу магазина.':'Войдите, чтобы открыть общую базу магазина.';$('#auth-submit').textContent=signup?'Создать аккаунт':'Войти';$('#auth-toggle').textContent=signup?'У меня уже есть аккаунт':'Создать аккаунт'}
async function enterApp(){
  $('#auth-page').hidden=true;$('#app-shell').hidden=false;$('#account-email').textContent=session.user?.email||'Аккаунт';setSyncStatus('','Загрузка облачной базы…');
  try{await loadCloudState();setSyncStatus('online','Данные синхронизированы')}catch(e){state=load(cacheKey());render();setSyncStatus('error','Нет связи с облаком');notice(`Облачная база недоступна: ${e.message}. Открыта локальная копия.`,true)}
}
async function loadCloudState(){
  const rows=await cloudFetch(`/rest/v1/store_state?select=data,revision&owner_id=eq.${encodeURIComponent(session.user.id)}`);
  if(rows.length){state={...emptyState(),...rows[0].data};cloudRevision=Number(rows[0].revision)||0}
  else{
    const initial=load(STORAGE_KEY);const created=await cloudFetch('/rest/v1/store_state',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({owner_id:session.user.id,data:initial,revision:0})});state={...emptyState(),...(created[0]?.data||initial)};cloudRevision=Number(created[0]?.revision)||0;
  }
  localStorage.setItem(cacheKey(),JSON.stringify(state));cloudDirty=false;render();
}
let saveChain=Promise.resolve();
function queueCloudSave(){if(!CLOUD_READY||!session)return;cloudDirty=true;saveChain=saveChain.then(syncCloudState).catch(()=>{})}
async function syncCloudState(){
  if(!cloudDirty||cloudSaving||!navigator.onLine)return;cloudSaving=true;cloudDirty=false;setSyncStatus('','Синхронизация…');const snapshot=structuredClone(state);
  try{
    const next=await cloudFetch('/rest/v1/rpc/save_store_state',{method:'POST',body:JSON.stringify({p_data:snapshot,p_expected_revision:cloudRevision})});cloudRevision=Number(next);localStorage.setItem(cacheKey(),JSON.stringify(snapshot));setSyncStatus('online','Данные синхронизированы');channel?.postMessage({revision:cloudRevision,state:snapshot});
  }catch(e){
    cloudDirty=true;setSyncStatus('error','Ошибка синхронизации');
    if(e.code==='40001'||String(e.message).includes('SYNC_CONFLICT')){localStorage.setItem(`${cacheKey()}:conflict:${Date.now()}`,JSON.stringify(snapshot));await loadCloudState();notice('Другой сеанс уже изменил базу. Загружена свежая версия; конфликтующая копия сохранена в браузере.',true)}else notice(`Не удалось синхронизировать: ${e.message}`,true);
  }finally{cloudSaving=false}
}
async function pollCloud(){if(!session||cloudDirty||cloudSaving||document.hidden||!navigator.onLine)return;try{const rows=await cloudFetch(`/rest/v1/store_state?select=data,revision&owner_id=eq.${encodeURIComponent(session.user.id)}`);if(rows[0]&&Number(rows[0].revision)>cloudRevision){state={...emptyState(),...rows[0].data};cloudRevision=Number(rows[0].revision);localStorage.setItem(cacheKey(),JSON.stringify(state));render();notice('Получены изменения из другого устройства.')}setSyncStatus('online','Данные синхронизированы')}catch{setSyncStatus('error','Нет связи с облаком')}}
const channel='BroadcastChannel'in window?new BroadcastChannel('magnat-flower-sync'):null;
channel?.addEventListener('message',event=>{if(event.data?.revision>cloudRevision&&!cloudDirty){cloudRevision=event.data.revision;state={...emptyState(),...event.data.state};localStorage.setItem(cacheKey(),JSON.stringify(state));render()}});
$('#auth-toggle').addEventListener('click',()=>{authMode=authMode==='login'?'signup':'login';$('#auth-error').textContent='';updateAuthMode()});
$('#logout').addEventListener('click',async()=>{try{await cloudFetch('/auth/v1/logout',{method:'POST'})}catch{}storeSession(null);state=emptyState();$('#app-shell').hidden=true;$('#auth-page').hidden=false;$('#auth-form').reset();updateAuthMode()});
window.addEventListener('online',()=>{setSyncStatus('','Восстановление связи…');queueCloudSave();void pollCloud()});
window.addEventListener('offline',()=>setSyncStatus('error','Нет интернета: изменения временно сохранены в браузере'));
document.addEventListener('visibilitychange',()=>{if(!document.hidden)void pollCloud()});
setInterval(()=>{if(cloudDirty)queueCloudSave();else void pollCloud()},15000);
async function startApp(){
  if(!CLOUD_READY){$('#auth-page').hidden=false;$('#setup-message').hidden=false;$('#setup-message').textContent='Облачная база ещё не подключена. Вставьте Project URL и anon key в начало файла app.js.';$('#auth-form').querySelectorAll('input,button').forEach(element=>element.disabled=true);$('#auth-toggle').disabled=true;return}
  const restored=await restoreSessionFromRedirect();
  if(!restored)try{session=JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch{session=null}
  if(session?.expires_at&&session.expires_at*1000<Date.now()+60000){try{await refreshSession()}catch{storeSession(null)}}
  if(session?.access_token)await enterApp();else{$('#auth-page').hidden=false;updateAuthMode()}
}
void startApp();

